// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmJIBu5uRlVFOtchaeY8CQ632vqK_TQC0',
    appId: '1:569959768889:web:71b0a9ffe918552c167ee8',
    messagingSenderId: '569959768889',
    projectId: 'instagram-6c624',
    authDomain: 'instagram-6c624.firebaseapp.com',
    storageBucket: 'instagram-6c624.appspot.com',
    measurementId: 'G-GSD33BGBQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgmqly8m5800UASeILVQI-aDtK2QGClTo',
    appId: '1:569959768889:android:ee3cce01680c1dd6167ee8',
    messagingSenderId: '569959768889',
    projectId: 'instagram-6c624',
    storageBucket: 'instagram-6c624.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhVPE0k4UTtd425n5lCvDaKsWDBPdVMys',
    appId: '1:569959768889:ios:1d9110e4f6b55d9d167ee8',
    messagingSenderId: '569959768889',
    projectId: 'instagram-6c624',
    storageBucket: 'instagram-6c624.appspot.com',
    iosClientId: '569959768889-1c7hh0djg1807kanl8vjmcbrk7af4ccv.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramRenewal',
  );
}
